# Stage1: Build React
FROM node:18 AS build
WORKDIR /frontend
RUN npm install
COPY . .

# Stage 2: Serve using nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
