services:
  db:
    image: postgres:15
    restart: always
    env_file: ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ifs-net

  backend:
    build:
      context: ./backend
    restart: always
    env_file: ./backend/.env
    environment:
      - DATABASE_HOSTNAME=db
    depends_on:
      - db
    networks:
      - ifs-net
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - ifs-net

volumes:
  postgres_data:

networks:
  ifs-net:
    driver: bridge
