version: '3'
services:
  postgresDB:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=feedback-system
      - POSTGRES_PASSWORD=cube
  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgresDB